apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phylax

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- cluster-issuer.yaml
- network-policy.yaml

configMapGenerator:
  - name: phylax-config
    behavior: create
    files:
    - phylax.yaml
