apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: phylax-prod

configMapGenerator:
- behavior: merge
  files:
  - phylax.yaml
  name: phylax-config
- envs:
  - .env
  name: phylax-env

patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: phylax
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: phylax-ingress
images:
- name: ghcr.io/phylax-systems/phylax
  newTag: v0.1.0-alpha.2
